travis:
  secure:
    BINSTAR_TOKEN: J5rUG3O4Nfrw3GChtLw13yuLbWpcrN+Kl2jS7Oden6LLRlvnZQNJStB+bPyX2mho5BNieVCf3Gf+7WbZ+dutM18xo/8BeBBPhqlt+YVkqfeIf2MwA9Zoe+v7EysaLbqXVzqFXOpteIEnycYsOy+vHK7Hq+HaJyt3x1myiVHTnpRGv2uUq7fhEGdonCyMMv/DZtjBLDdnsnnnHVcDAMKHqcmJdOuq2h9NOk0GdyrrHQAVG5xeyluf3bIM/+liaFHs5TSrqvDTRBA7rtYH1iyX/mfUlKCOeM7ehn9JT+7TeopXKqlFN5eNCam7sFuw7UGHmtqq0+/eAokeQOGJ9RM/DQaFHGOye8JQD7hct8ySFu8viwJPzsvuVoIvb7FsK0lbMNAmPRGSkNYvVGtfVglQNyy/kljRLFSRI4ISbcLUPZeywB+B4YgAH4rwTuJ67PHe7ieyjeNfWrrP1Am2jyccxeWDNHBrZZI4y2weySbWPrPk11/s8NMSM1/pe+b0iPi2Kr5D4lQAixTfb0hPYJGYhqX4D6Ik2WeZH0BAAj/TnGDH9iKWH3Qb8SsP03nlsIY3pbDR4mAQg9BhNx+so7hBA0pEv/KM9/H55pEADlZv+HA+2mVHnKDmyfNfg0mRS0a31DD1VSSYjxwygLUaaRIoR7QgiKR57Oi47SrI+p1VC10=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
